name: sepuh
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  mongo_dart: ^0.10.3
  http: ^1.2.2
  json_annotation: ^4.9.0
  flutter_secure_storage: ^4.2.1
  jwt_decode: ^0.3.1
  bcrypt: ^1.1.3
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  multi_select_flutter: ^4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/doctor.png
    - assets/schedule.png
    - assets/registP.png
    - assets/logoLogin.png
    - assets/logo.png
    - assets/success.png
    - assets/board1.png
    - assets/board2.png
    - assets/board3.png
    - assets/dokterr.png
    - assets/pasien.png
    - assets/meds.png